apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: <NAMESPACE>
spec:
  kafka:
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: <PVC_SIZE>
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    metrics:
      lowercaseOutputName: true
      rules:
        - pattern: kafka.controller<type=KafkaController, name=OfflinePartitionsCount><>Value
          name: kafka_controller_kafkacontroller_offline_partitions_count
          type: GAUGE
        - pattern: kafka.server<type=ReplicaManager, name=UnderReplicatedPartitions><>Value
          name: kafka_server_replicamanager_under_replicated_partitions
          type: GAUGE
        - pattern: kafka.server<type=ReplicaManager, name=AtMinIsrPartitionCount><>Value
          name: kafka_server_replicamanager_at_min_isr_partition_count
          type: GAUGE
        - pattern: kafka.cluster<type=Partition, name=AtMinIsr, topic=(\w+), partition=(.*)><>Value
          name: kafka_cluster_partition_at_min_isr
          type: GAUGE
          labels:
            topic: "$1"
            partition: "$2"
        - pattern: kafka.server<type=ReplicaManager, name=UnderMinIsrPartitionCount><>Value
          name: kafka_server_replicamanager_under_min_isr_partition_count
          type: GAUGE
        - pattern: kafka.cluster<type=Partition, name=UnderMinIsr, topic=(\w+), partition=(.*)><>Value
          name: kafka_cluster_partition_under_min_isr
          type: GAUGE
          labels:
            topic: "$1"
            partition: "$2"
        - pattern: kafka.controller<type=KafkaController, name=ActiveControllerCount><>Value
          name: kafka_controller_kafkacontroller_active_controller_count
          type: GAUGE
        - pattern: kafka.server<type=ReplicaManager, name=LeaderCount><>Value
          name: kafka_server_replicamanager_leader_count
          type: GAUGE
        - pattern: kafka.server<type=BrokerTopicMetrics, name=BytesInPerSec, topic=(\w+)><>Count
          name: kafka_server_brokertopicmetrics_bytes_in_total
          type: GAUGE
          labels:
            topic: "$1"
        - pattern: kafka.server<type=BrokerTopicMetrics, name=BytesOutPerSec, topic=(\w+)><>Count
          name: kafka_server_brokertopicmetrics_bytes_out_total
          type: GAUGE
          labels:
            topic: "$1"
        - pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec, topic=(\w+)><>Count
          name: kafka_server_brokertopicmetrics_messages_in_total
          type: GAUGE
          labels:
            topic: "$1"
        # yields $2 types of percentiles, count, mean, max, min, stddev
        - pattern: kafka.network<type=RequestMetrics, name=TotalTimeMs, request=(\w+)><>(\w+)
          name: kafka_network_requestmetrics_total_time_ms_$2
          type: GAUGE
          labels:
            request: "$1"
        - pattern: kafka.controller<type=KafkaController, name=GlobalPartitionCount><>Value
          name: kafka_controller_kafkacontroller_global_partition_count
          type: GAUGE
        - pattern: kafka.log<type=Log, name=Size, topic=(\w+), partition=(.*)><>Value
          name: kafka_log_log_size
          type: GAUGE
          labels:
            topic: "$1"
            partition: "$2"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: <PVC_SIZE>
      deleteClaim: false
    metrics:
      lowercaseOutputName: true
      rules:
        - pattern: org.apache.ZooKeeperService<(.*)><>OutstandingRequests
          name: zookeeper_outstanding_requests
          type: GAUGE
          labels:
            names: ($1)
        - pattern: org.apache.ZooKeeperService<(.*)><>AvgRequestLatency
          name: zookeeper_request_avg_latency
          type: GAUGE
          labels:
            names: ($1)
        - pattern: org.apache.ZooKeeperService<(.*)><>QuorumSize
          name: zookeeper_quorum_size
          type: GAUGE
          labels:
            names: ($1)
  entityOperator:
    topicOperator: {}
    userOperator: {}
