---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: <name>
  namespace: <namespace>
spec:
  config:
    auth:
      disable_login_form: false
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - kafka-fleet
  ingress:
    enabled: true
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: <name>
  namespace: <namespace>
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
        tlsSkipVerify: true
      name: Thanos
      type: prometheus
      url: 'http://<querier>.<namespace>.svc.cluster.local:9008'
      version: 1
  name: kafka.yaml
