apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: grafanadatasource
spec:
  name: middleware.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: https://prometheus-k8s.openshift-monitoring.svc:9091
      basicAuth: true
      basicAuthPassword: OcC5yjE+8pAv4I7UjiJ0cTz9hyb+/+GFbaUqFdg543XBdrylhlAxS+ZfQEZHb3XFWlE15DYn8laPwhsHxAMFFC75UYN5PZYFH0ADgcgEmH1XJ8bwLmIT8OBcPyCrO8t+qqb/YisT698mahI95IuZWSbKCAHC3oMTcpIUnqMASCMH2ltWVaEbCgq+noHcL+kI6qt9OkBxqip5fZ923ifEFdTaN7onP8GGW51ekRHbJ2EVTIyuVC/nFMFhtXx8Ph+IkI5RmnZtXY5/DTmWHZAN7mDKvzc4tqjvj8r4gmwvJSgdDcufDdlBOYxSu+DhucbZeFrJ4+x0HeBIlSmFHiYF
      basicAuthUser: internal
      isDefault: true
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
