# This is a list of rule files to consider for testing. Globs are supported.
rule_files:
  - prometheus-rules-groups.yaml

# optional, default = 1m
evaluation_interval: 1m

# The order in which group names are listed below will be the order of evaluation of
# rule groups (at a given evaluation time). The order is guaranteed only for the groups mentioned below.
# All the groups need not be mentioned below.
# group_eval_order:
#   [ - <group_name> ]

tests:
    # 99% SLO, burn rate of just over 1.
    # This means just over 1% of requests are errors over 6h i.e.
    # - 7 failed requests per 600 total every minute for 6h
    # - 0 failed requests thereafter
    - interval: 1m
      input_series:
          - series: 'kafka_server_brokertopicmetrics_failed_produce_requests_total'
            values: '0+7x360'
          - series: 'kafka_server_brokertopicmetrics_total_produce_requests_total'
            values: '0+600x360 216000+600x360'
      alert_rule_test:
          # Warning should fire after 6h short window.
          - eval_time: 6h
            alertname: ErrorBudgetBurn_ProduceRequests_6hS3dL
            exp_alerts:
                - exp_labels:
                      severity: warning
                  exp_annotations:
                      message: "High error budget burn for failed produce requests during 6h short window, 3d long window. (current value: 0.011666666666666667)"
          # No alerts after 6h with 0 failed requests
          - eval_time: 12h
            alertname: ErrorBudgetBurn_ProduceRequests_6hS3dL
    # 99% SLO, burn rate of just over 3.
    # This means just over 3% of requests are errors over 3h i.e.
    # - 19 failed requests per 600 total every minute for 3h
    # - 0 failed requests thereafter
    - interval: 1m
      input_series:
          - series: 'kafka_server_brokertopicmetrics_failed_produce_requests_total'
            values: '0+19x120'
          - series: 'kafka_server_brokertopicmetrics_total_produce_requests_total'
            values: '0+600x120 72000+600x120'
      alert_rule_test:
          # Warning should fire after 2h short window.
          - eval_time: 2h
            alertname: ErrorBudgetBurn_ProduceRequests_2hS1dL
            exp_alerts:
                - exp_labels:
                      severity: warning
                  exp_annotations:
                      message: "High error budget burn for failed produce requests during 2h short window, 1d long window. (current value: 0.03166666666666667)"
          # No alerts after 2h with 0 failed requests
          - eval_time: 4h
            alertname: ErrorBudgetBurn_ProduceRequests_2hS1dL     
    # 99% SLO, burn rate of just over 6.
    # This means just over 15% of requests are errors over 6h i.e.
    # - 150 failed requests per 600 total every minute for 6h
    # - 0 failed requests thereafter
    - interval: 1m
      input_series:
          - series: 'kafka_server_brokertopicmetrics_failed_produce_requests_total'
            values: '0+150x30'
          - series: 'kafka_server_brokertopicmetrics_total_produce_requests_total'
            values: '0+600x30 18000+600x30'
      alert_rule_test:
          # Warning should fire after 30m short window.
          - eval_time: 30m
            alertname: ErrorBudgetBurn_ProduceRequests_30mS6hL
            exp_alerts:
                - exp_labels:
                      severity: critical
                  exp_annotations:
                      message: "High error budget burn for failed produce requests during 30m short window, 6h long window. (current value: 0.25)"
          # No alerts after 1h30m with 0 failed requests
          - eval_time: 1h30m
            alertname: ErrorBudgetBurn_ProduceRequests_30mS6hL   
    # 99% SLO, burn rate of just over 14.40.
    # This means just over 14.4% of requests are errors over 14.40 i.e.
    # - 87 failed requests per 600 total every minute for 1h
    # - 0 failed requests thereafter
    - interval: 1m
      input_series:
          - series: 'kafka_server_brokertopicmetrics_failed_produce_requests_total'
            values: '0+87x5'
          - series: 'kafka_server_brokertopicmetrics_total_produce_requests_total'
            values: '0+600x5 30000+600x5'
      alert_rule_test:
          # Warning should fire after 5m short window.
          - eval_time: 5m
            alertname: ErrorBudgetBurn_ProduceRequests_5mS1hL
            exp_alerts:
                - exp_labels:
                      severity: critical
                  exp_annotations:
                      message: "High error budget burn for failed produce requests during 5m short window, 1h long window. (current value: 0.145)"
          # No alerts after 5m with 0 failed requests
          - eval_time: 10m
            alertname: ErrorBudgetBurn_ProduceRequests_5mS1hL                   
    